#!/bin/bash

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Update system.
apt update
apt upgrade -y
apt dist-upgrade -y

# Remove desktop.
apt install -y tasksel
tasksel
apt update
apt autoremove -y
apt clean all

# Re-update system.
apt update
apt upgrade -y
apt dist-upgrade -y
